

version: '3.8'

services:
  db:
    image: 'postgres:latest'
    container_name: 'db'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5432:5432"
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: 'app'
    depends_on:
      - 'db'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.1:5432/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

    ports:
      - "8080:8080"
